name: Docker CI

on: push
jobs:
  docker:
    if: contains(github.event.commits[0].message, '[build]')
    name: Build and push Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Login to GitHub Packages
      #   run: echo ${{ secrets.GH_TOKEN }} | docker login docker.pkg.github.com -u kw7oe --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=version::$(grep 'version:' mix.exs | cut -d '"' -f2)
      - name: Print the version
        run: echo ${{steps.vars.output.version}}
      # - name: Build the tagged Docker image
      #   run: docker build . -t mini
